# Generated by Django 5.0.6 on 2024-09-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_catagory_alter_article_options_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cataogry',
            field=models.ManyToManyField(to='Article.catagory', verbose_name='دسته بندی'),
        ),
    ]
